### ISSUE TITLE
NuGet Package Title Case Incorrect

### ISSUE THREAD

**Issue by nnpcYvIVl** [cezarypiatek/ExceptionAnalyzer#13]
The nuget package https://www.nuget.org/packages/SmartAnalyzers.ExceptionAnalyzer/ is named with the wrong case `SmartanAlyzers.ExceptionAnalyzer`. It should be renamed to `SmartaAnalyzers.ExceptionAnalyzer`.

**Comment by cezarypiatek** [comment]
The package id was fixed but nuget.org keeps Package Id from the first release. This cannot be fixed. However, VS displays it correctly

![image](https://user-images.githubusercontent.com/7759991/63285400-eb0ede00-c2b5-11e9-9540-4fd09a2f2167.png)
